package com.xdpsx.ecommerce.auth.infrastructure.security;

import static org.assertj.core.api.Assertions.assertThat;

import javax.crypto.spec.SecretKeySpec;

import org.junit.jupiter.api.Test;
import org.springframework.security.oauth2.jose.jws.MacAlgorithm;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.test.util.ReflectionTestUtils;

import com.nimbusds.jose.JWSAlgorithm;
import com.xdpsx.ecommerce.user.domain.AuthProvider;
import com.xdpsx.ecommerce.user.domain.Role;

/**
 * Guards that a token generated by {@link TokenProvider} is still accepted by the decoder configured in
 * {@code SecurityConfig} after the Spring Security 7 / Nimbus JOSE JWT upgrade.
 *
 * <p>Mirrors the production wiring without starting an application context: same HS256 secret key, same
 * {@code NimbusJwtDecoder.withSecretKey(...)} configuration.
 */
class TokenProviderJwtDecoderTest {

    private static final String SECRET_KEY = "test-secret-key-that-is-long-enough-for-hs256";

    private TokenProvider tokenProvider() {
        TokenProvider tokenProvider = new TokenProvider();
        ReflectionTestUtils.setField(tokenProvider, "SECRET_KEY", SECRET_KEY);
        ReflectionTestUtils.setField(tokenProvider, "EXPIRATION_SECONDS", 3600L);
        return tokenProvider;
    }

    private JwtDecoder jwtDecoder() {
        SecretKeySpec secretKeySpec = new SecretKeySpec(SECRET_KEY.getBytes(), JWSAlgorithm.HS256.getName());
        return NimbusJwtDecoder.withSecretKey(secretKeySpec)
                .macAlgorithm(MacAlgorithm.HS256)
                .build();
    }

    @Test
    void generatedToken_shouldBeDecodableByConfiguredDecoder() {
        CustomUserDetails user = CustomUserDetails.builder()
                .id(1L)
                .username("user@example.com")
                .authProvider(AuthProvider.LOCAL)
                .role(Role.USER)
                .build();

        String token = tokenProvider().generateToken(user);
        Jwt jwt = jwtDecoder().decode(token);

        assertThat(jwt.getSubject()).isEqualTo("user@example.com");
        assertThat(jwt.getClaimAsString("scope")).isEqualTo("ROLE_USER");
        assertThat(jwt.getExpiresAt()).isAfter(jwt.getIssuedAt());
    }
}
